rootProject.name = "riemann"

include(":java")
include(":java:etc")
include(":java:etc:excel")
include(":java:generics")

include(":spring")
include(":spring:library")
include(":spring:library:jpa")
include(":spring:application")
include(":spring:application:module")
include(":spring:application:module:aop-reflection")
include(":spring:application:module:async")
include(":spring:application:module:cache")
include(":spring:application:module:resilience4j")
include(":spring:application:module:resilience4j:springboot2")
include(":spring:application:module:reactive")
include(":spring:application:module:rest-docs")
include(":spring:application:api-web")
